import 'package:get/get.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:snap_journey/model/TagStyle.dart';

class TagStyleController extends GetxController {
  var selectedStyleId = 1.obs;
  var styles = <TagStyle>[].obs;
  var selectedStyle = Rxn<TagStyle>();

  @override
  void onInit() {
    super.onInit();
    _loadStyles();
    _loadSelectedStyle();
  }


  void _loadStyles() {
    styles.value = [
      TagStyle(
        id: 1,
        name: 'Classic Location',
        description: 'Clean modern location card with subtle shadow',
        layoutType: TagLayoutType.standard,
        styleType: TagStyleType.classic,
        borderRadius: 20,
        elevation: 8,
        opacity: 0.95,
        paddingHorizontal: 20,
        paddingVertical: 16,
        fontSize: 14,
        iconSize: 24,
        showIcon: true,
        showWeather: false,
        showCoordinates: false,
        showDateTime: true,
        titleFontSize: 18,
        subtitleFontSize: 13,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 2,
        name: 'Compact Modern',
        description: 'Minimalist card with essential info only',
        layoutType: TagLayoutType.compact,
        styleType: TagStyleType.modern,
        borderRadius: 16,
        elevation: 4,
        opacity: 0.9,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 13,
        iconSize: 20,
        showIcon: true,
        showWeather: false,
        showCoordinates: true,
        showDateTime: true,
        titleFontSize: 16,
        subtitleFontSize: 12,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 3,
        name: 'Minimal Clean',
        description: 'Ultra-minimal transparent overlay',
        layoutType: TagLayoutType.minimal,
        styleType: TagStyleType.transparent,
        borderRadius: 12,
        elevation: 2,
        opacity: 0.7,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 12,
        iconSize: 18,
        showIcon: false,
        showWeather: false,
        showCoordinates: false,
        showDateTime: true,
        titleFontSize: 15,
        subtitleFontSize: 11,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 4,
        name: 'Detailed Pro',
        description: 'Complete location information with weather',
        layoutType: TagLayoutType.detailed,
        styleType: TagStyleType.material,
        borderRadius: 18,
        elevation: 10,
        opacity: 0.98,
        paddingHorizontal: 20,
        paddingVertical: 18,
        fontSize: 14,
        iconSize: 24,
        showIcon: true,
        showWeather: true,
        showCoordinates: true,
        showDateTime: true,
        titleFontSize: 20,
        subtitleFontSize: 14,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 5,
        name: 'Weather Focus',
        description: 'Weather-centric design with rounded corners',
        layoutType: TagLayoutType.weather,
        styleType: TagStyleType.rounded,
        borderRadius: 30,
        elevation: 6,
        opacity: 0.9,
        paddingHorizontal: 18,
        paddingVertical: 16,
        fontSize: 13,
        iconSize: 28,
        showIcon: true,
        showWeather: true,
        showCoordinates: false,
        showDateTime: true,
        titleFontSize: 18,
        subtitleFontSize: 13,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 6,
        name: 'GPS Precision',
        description: 'Coordinates-focused sharp design',
        layoutType: TagLayoutType.coordinates,
        styleType: TagStyleType.sharp,
        borderRadius: 8,
        elevation: 4,
        opacity: 1.0,
        paddingHorizontal: 20,
        paddingVertical: 16,
        fontSize: 13,
        iconSize: 22,
        showIcon: true,
        showWeather: false,
        showCoordinates: true,
        showDateTime: true,
        titleFontSize: 16,
        subtitleFontSize: 12,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 7,
        name: 'Frosted Glass',
        description: 'Beautiful blur glassmorphism effect',
        layoutType: TagLayoutType.detailed,
        styleType: TagStyleType.glassy,
        borderRadius: 24,
        elevation: 0,
        opacity: 0.8,
        paddingHorizontal: 24,
        paddingVertical: 20,
        fontSize: 14,
        iconSize: 26,
        showIcon: true,
        showWeather: true,
        showCoordinates: true,
        showDateTime: true,
        blurRadius: 15,
        hasGradient: true,
        titleFontSize: 19,
        subtitleFontSize: 14,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 8,
        name: 'Soft Overlay',
        description: 'Elegant semi-transparent overlay',
        layoutType: TagLayoutType.standard,
        styleType: TagStyleType.overlay,
        borderRadius: 20,
        elevation: 0,
        opacity: 0.6,
        paddingHorizontal: 18,
        paddingVertical: 14,
        fontSize: 13,
        iconSize: 22,
        showIcon: true,
        showWeather: false,
        showCoordinates: false,
        showDateTime: true,
        overlayColor: 'rgba(255,255,255,0.85)',
        titleFontSize: 17,
        subtitleFontSize: 12,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 9,
        name: 'Cyber Neon',
        description: 'Vibrant neon glow effect',
        layoutType: TagLayoutType.compact,
        styleType: TagStyleType.modern,
        borderRadius: 16,
        elevation: 12,
        opacity: 0.95,
        paddingHorizontal: 20,
        paddingVertical: 16,
        fontSize: 14,
        iconSize: 24,
        showIcon: true,
        showWeather: true,
        showCoordinates: false,
        showDateTime: true,
        overlayColor: 'rgba(0,255,255,0.4)',
        hasGradient: true,
        titleFontSize: 18,
        subtitleFontSize: 13,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 10,
        name: 'Vintage Retro',
        description: 'Classic sepia-toned vintage look',
        layoutType: TagLayoutType.standard,
        styleType: TagStyleType.classic,
        borderRadius: 12,
        elevation: 6,
        opacity: 0.9,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 13,
        iconSize: 20,
        showIcon: false,
        showWeather: false,
        showCoordinates: true,
        showDateTime: true,
        overlayColor: 'rgba(160,105,67,0.6)',
        titleFontSize: 17,
        subtitleFontSize: 12,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 11,
        name: 'Dark Mode',
        description: 'Sleek dark minimalist design',
        layoutType: TagLayoutType.minimal,
        styleType: TagStyleType.transparent,
        borderRadius: 0,
        elevation: 0,
        opacity: 0.8,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 14,
        iconSize: 20,
        showIcon: true,
        showWeather: false,
        showCoordinates: false,
        showDateTime: false,
        overlayColor: 'rgba(30,30,30,0.9)',
        titleFontSize: 18,
        subtitleFontSize: 13,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 12,
        name: 'Luxury Gold',
        description: 'Premium golden elegant design',
        layoutType: TagLayoutType.detailed,
        styleType: TagStyleType.rounded,
        borderRadius: 28,
        elevation: 8,
        opacity: 0.95,
        paddingHorizontal: 22,
        paddingVertical: 18,
        fontSize: 14,
        iconSize: 24,
        showIcon: true,
        showWeather: true,
        showCoordinates: true,
        showDateTime: true,
        hasGradient: true,
        titleFontSize: 20,
        subtitleFontSize: 14,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 13,
        name: 'Sunset Glow',
        description: 'Warm sunset gradient overlay',
        layoutType: TagLayoutType.weather,
        styleType: TagStyleType.overlay,
        borderRadius: 22,
        elevation: 6,
        opacity: 0.85,
        paddingHorizontal: 18,
        paddingVertical: 16,
        fontSize: 13,
        iconSize: 24,
        showIcon: true,
        showWeather: true,
        showCoordinates: false,
        showDateTime: true,
        overlayColor: 'rgba(255,140,0,0.7)',
        hasGradient: true,
        titleFontSize: 18,
        subtitleFontSize: 13,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 14,
        name: 'Crystal Clear',
        description: 'High blur glass effect',
        layoutType: TagLayoutType.coordinates,
        styleType: TagStyleType.glassy,
        borderRadius: 26,
        elevation: 0,
        opacity: 0.6,
        paddingHorizontal: 20,
        paddingVertical: 16,
        fontSize: 13,
        iconSize: 22,
        showIcon: true,
        showWeather: false,
        showCoordinates: true,
        showDateTime: true,
        blurRadius: 20,
        titleFontSize: 17,
        subtitleFontSize: 12,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 15,
        name: 'Bold Impact',
        description: 'High contrast sharp design',
        layoutType: TagLayoutType.standard,
        styleType: TagStyleType.sharp,
        borderRadius: 0,
        elevation: 12,
        opacity: 1.0,
        paddingHorizontal: 24,
        paddingVertical: 20,
        fontSize: 16,
        iconSize: 28,
        showIcon: true,
        showWeather: true,
        showCoordinates: true,
        showDateTime: true,
        overlayColor: 'rgba(255,255,255,0.95)',
        titleFontSize: 22,
        subtitleFontSize: 15,
        category: TagCategory.location,
      ),
      TagStyle(
        id: 16,
        name: 'Line Flow',
        description: 'Creative fade line design',
        layoutType: TagLayoutType.lineFade,
        styleType: TagStyleType.modern,
        borderRadius: 0,
        elevation: 0,
        opacity: 0.0,
        paddingHorizontal: 0,
        paddingVertical: 16,
        fontSize: 16,
        iconSize: 0,
        showIcon: false,
        showWeather: false,
        showCoordinates: false,
        showDateTime: false,
        hasGradient: true,
        titleFontSize: 20,
        subtitleFontSize: 14,
        category: TagCategory.location,
      ),

      // ENHANCED FILTERS (17-26) - Snapchat-style cinematic filters
      TagStyle(
        id: 17,
        name: 'Cinematic Warm',
        description: 'Soft warm orange cinematic tone',
        layoutType: TagLayoutType.timeFocused,
        styleType: TagStyleType.modern,
        borderRadius: 25,
        elevation: 6,
        opacity: 0.9,
        paddingHorizontal: 24,
        paddingVertical: 20,
        fontSize: 18,
        iconSize: 0,
        showIcon: false,
        showWeather: false,
        showCoordinates: false,
        showDateTime: true,
        overlayColor: 'rgba(255,180,120,0.3)',
        hasGradient: true,
        titleFontSize: 28,
        subtitleFontSize: 18,
        category: TagCategory.filters,
      ),
      TagStyle(
        id: 18,
        name: 'Cinematic Cool',
        description: 'Teal blue cinematic shadows',
        layoutType: TagLayoutType.dateFocused,
        styleType: TagStyleType.rounded,
        borderRadius: 35,
        elevation: 8,
        opacity: 0.85,
        paddingHorizontal: 28,
        paddingVertical: 24,
        fontSize: 20,
        iconSize: 0,
        showIcon: false,
        showWeather: false,
        showCoordinates: false,
        showDateTime: true,
        overlayColor: 'rgba(0,200,255,0.4)',
        hasGradient: true,
        titleFontSize: 32,
        subtitleFontSize: 20,
        category: TagCategory.filters,
      ),
      TagStyle(
        id: 19,
        name: 'Sepia Classic',
        description: 'Vintage brown sepia filter',
        layoutType: TagLayoutType.standard,
        styleType: TagStyleType.classic,
        borderRadius: 20,
        elevation: 4,
        opacity: 0.9,
        paddingHorizontal: 20,
        paddingVertical: 16,
        fontSize: 16,
        iconSize: 24,
        showIcon: true,
        showWeather: false,
        showCoordinates: false,
        showDateTime: true,
        overlayColor: 'rgba(160,120,80,0.6)',
        titleFontSize: 22,
        subtitleFontSize: 15,
        category: TagCategory.filters,
      ),
      TagStyle(
        id: 20,
        name: 'Vignette Edge',
        description: 'Dark edges bright center effect',
        layoutType: TagLayoutType.compact,
        styleType: TagStyleType.overlay,
        borderRadius: 22,
        elevation: 6,
        opacity: 0.8,
        paddingHorizontal: 22,
        paddingVertical: 18,
        fontSize: 15,
        iconSize: 22,
        showIcon: true,
        showWeather: false,
        showCoordinates: true,
        showDateTime: true,
        overlayColor: 'rgba(0,0,0,0.7)',
        hasGradient: true,
        titleFontSize: 24,
        subtitleFontSize: 16,
        category: TagCategory.filters,
      ),
      TagStyle(
        id: 21,
        name: 'Light Leak',
        description: 'Film light leak gradient streaks',
        layoutType: TagLayoutType.weather,
        styleType: TagStyleType.glassy,
        borderRadius: 28,
        elevation: 0,
        opacity: 0.7,
        paddingHorizontal: 24,
        paddingVertical: 20,
        fontSize: 16,
        iconSize: 26,
        showIcon: true,
        showWeather: true,
        showCoordinates: false,
        showDateTime: false,
        blurRadius: 10,
        hasGradient: true,
        titleFontSize: 26,
        subtitleFontSize: 17,
        category: TagCategory.filters,
      ),
      TagStyle(
        id: 22,
        name: 'Neon Pop',
        description: 'Vibrant neon color boost',
        layoutType: TagLayoutType.coordinates,
        styleType: TagStyleType.modern,
        borderRadius: 18,
        elevation: 10,
        opacity: 0.95,
        paddingHorizontal: 20,
        paddingVertical: 16,
        fontSize: 15,
        iconSize: 24,
        showIcon: true,
        showWeather: false,
        showCoordinates: true,
        showDateTime: false,
        overlayColor: 'rgba(255,0,255,0.5)',
        hasGradient: true,
        titleFontSize: 25,
        subtitleFontSize: 16,
        category: TagCategory.filters,
      ),
      TagStyle(
        id: 23,
        name: 'Pastel Dream',
        description: 'Soft pastel color overlay',
        layoutType: TagLayoutType.detailed,
        styleType: TagStyleType.rounded,
        borderRadius: 32,
        elevation: 6,
        opacity: 0.8,
        paddingHorizontal: 26,
        paddingVertical: 22,
        fontSize: 16,
        iconSize: 24,
        showIcon: true,
        showWeather: true,
        showCoordinates: true,
        showDateTime: true,
        overlayColor: 'rgba(200,200,255,0.4)',
        hasGradient: true,
        titleFontSize: 24,
        subtitleFontSize: 16,
        category: TagCategory.filters,
      ),
      TagStyle(
        id: 24,
        name: 'Monochrome',
        description: 'Classic black & white filter',
        layoutType: TagLayoutType.minimal,
        styleType: TagStyleType.sharp,
        borderRadius: 0,
        elevation: 0,
        opacity: 1.0,
        paddingHorizontal: 18,
        paddingVertical: 14,
        fontSize: 17,
        iconSize: 0,
        showIcon: false,
        showWeather: false,
        showCoordinates: false,
        showDateTime: true,
        overlayColor: 'rgba(255,255,255,0.9)',
        titleFontSize: 26,
        subtitleFontSize: 18,
        category: TagCategory.filters,
      ),
      TagStyle(
        id: 25,
        name: 'Orange Glow',
        description: 'Warm orange subject highlighting',
        layoutType: TagLayoutType.standard,
        styleType: TagStyleType.overlay,
        borderRadius: 24,
        elevation: 8,
        opacity: 0.9,
        paddingHorizontal: 22,
        paddingVertical: 18,
        fontSize: 16,
        iconSize: 26,
        showIcon: true,
        showWeather: true,
        showCoordinates: false,
        showDateTime: true,
        overlayColor: 'rgba(255,140,0,0.6)',
        hasGradient: true,
        titleFontSize: 27,
        subtitleFontSize: 18,
        category: TagCategory.filters,
      ),
      TagStyle(
        id: 26,
        name: 'Soft Blur',
        description: 'Dreamy soft blur effect',
        layoutType: TagLayoutType.timeFocused,
        styleType: TagStyleType.glassy,
        borderRadius: 30,
        elevation: 0,
        opacity: 0.7,
        paddingHorizontal: 28,
        paddingVertical: 24,
        fontSize: 18,
        iconSize: 0,
        showIcon: false,
        showWeather: false,
        showCoordinates: false,
        showDateTime: true,
        blurRadius: 8,
        hasGradient: true,
        titleFontSize: 22,
        subtitleFontSize: 16,
        category: TagCategory.filters,
      ),
    ];
    _updateSelectedStyle();
  }

  Future<void> _loadSelectedStyle() async {
    final prefs = await SharedPreferences.getInstance();
    selectedStyleId.value = prefs.getInt('selectedStyleId') ?? 1;
    _updateSelectedStyle();
  }

  void _updateSelectedStyle() {
    final style = styles.firstWhereOrNull((s) => s.id == selectedStyleId.value);
    selectedStyle.value = style ?? styles[0];
  }

  void selectStyle(int styleId) {
    final style = styles.firstWhereOrNull((s) => s.id == styleId);
    if (style != null) {
      selectedStyleId.value = styleId;
      SharedPreferences.getInstance().then(
            (prefs) => prefs.setInt('selectedStyleId', styleId),
      );
      _updateSelectedStyle();
      update();
    }
  }

  void toggleTag(bool enabled) {
    update();
  }
}
